---
{{ if .prod_cluster }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes ingress over service IP
  labels:
    run: haproxy-ingress
  name: haproxy-svc-bgp
  namespace: ingress-controller
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: haproxy-ingress
  type: LoadBalancer
  loadBalancerIP: {{ .bgp_cluster_ip  }}
{{ end }}