---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-status
  namespace: ingress-controller
  labels:
    app: haproxy-status
spec:
  ports:
    - name: status
      protocol: TCP
      port: 1936
      targetPort: 1936
  selector:
    run: haproxy-ingress
